import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mini Instagram",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children}: {children: React.ReactNode}) {
  return (
    <html>
      <body>
        {children}
        <div id="modal-root" />
      </body>
    </html>
  );
}